driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
- name: ubuntu
  driver_config:
    privileged: true
    memory: 256m
    provision_command:
    - echo "root:password" | chpasswd
    - sed -i 's/Defaults   requiretty/#Defaults   requiretty/g' /etc/sudoers
    - "apt-get install -y cron build-essential"

suites:
- name: default
  run_list:
  - recipe[supervisor]
